apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    name: dex
  name: dex
  namespace: auth
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
