apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    name: dex
  name: dex
  namespace: auth
spec:
  dnsNames:
  - dex.INSERT_OWN_DOMAIN.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: dex-tls