apiVersion: v1
data:
  config.yaml: |-
    issuer: https://dex.auth.svc.cluster.local:5558
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
      https: 0.0.0.0:5558
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    grpc:
      addr: 127.0.0.1:5557
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
      tlsClientCA: /etc/dex/tls/tls.crt
    enablePasswordDB: true
    staticClients:
    - id: gangway-oauth2client
      redirectURIs:
      - https://aakindele-retaildevcrews-aks-oidc-proxy-pq7qx6r2rp6v-30080.githubpreview.dev/callback
      name: gangway-oauth2client
      secret: a5eedbeff37df5eeb67af65f # random String. `openssl rand -hex 12`
    staticPasswords:
    - email: user@example.com # E-mail address to allow authentication to
      hash: "$2y$10$i3ogbGtHh95sSaDspnBac.FyQDbFJPJztSrronV7BSUxdJmpHUGHS" # bcrypt(10r) for "password". `htpasswd -nbBC 10 "" password | tr -d ':\n'`
      username: user@example.com # E-mail address to allow authentication to
      userID: user@example.com # E-mail address to allow authentication to
kind: ConfigMap
metadata:
  labels:
    name: dex
  name: dex
  namespace: auth
