apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    name: dex
  name: dex
  namespace: auth
spec:
  dnsNames:
  - dex.auth.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: my-ca-issuer
  secretName: dex-tls
