apiVersion: v1
data:
  config.yaml: |-
    issuer: http://dex.auth.svc.cluster.local:5556
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    grpc:
      addr: 127.0.0.1:5557
    enablePasswordDB: true
    staticClients:
    - id: gangway
      redirectURIs:
      - https://gangway.INSERT_OWN_DOMAIN.HERE/callback
      name: gangway-oauth2client
      secret: a5eedbeff37df5eeb67af65f # random String. `openssl rand -hex 12`
    staticPasswords:
    - email: user@INSERT_OWN_DOMAIN.HERE # E-mail address to allow authentication to
      hash: "$2y$10$i3ogbGtHh95sSaDspnBac.FyQDbFJPJztSrronV7BSUxdJmpHUGHS" # bcrypt(10r) for "password". `htpasswd -nbBC 10 "" password | tr -d ':\n'`
      username: user@INSERT_OWN_DOMAIN.HERE # E-mail address to allow authentication to
      userID: user@INSERT_OWN_DOMAIN.HERE # E-mail address to allow authentication to
kind: ConfigMap
metadata:
  labels:
    name: dex
  name: dex
  namespace: auth
