apiVersion: v1
data:
  config.yaml: |-
    issuer: https://dex.INSERT_OWN_DOMAIN.HERE
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    grpc:
      addr: 127.0.0.1:5557
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
      tlsClientCA: /etc/dex/tls/tls.crt
    enablePasswordDB: true
kind: ConfigMap
metadata:
  labels:
    name: dex
  name: dex
  namespace: auth