apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    name: kube-oidc-proxy
  name: kube-oidc-proxy
  namespace: auth
spec:
  dnsNames:
  - kube-oidc-proxy.INSERT_OWN_DOMAIN.HERE
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: kube-oidc-proxy-tls