apiVersion: v1
kind: Service
metadata:
  name: kube-oidc-proxy
spec:
  type: ClusterIP
  ports:
  - name: kube-oidc-proxy
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    name: kube-oidc-proxy