apiVersion: v1
data:
  oidc.client-id: NzVVaU8yRTgxbTVWaTNuU1Q0MjY5ZnVP
  oidc.issuer-url: aHR0cHM6Ly9kZXguZXZpbGxnZW5pdXMuY29t
kind: Secret
metadata:
  labels:
    name: kube-oidc-proxy-config
  name: kube-oidc-proxy-config
  namespace: auth
type: Opaque
