apiVersion: v1
data:
  oidc.client-id: Z2FuZ3dheQ== # Base64 encoded version of DEX staticClient config ClientID
  oidc.issuer-url: aHR0cHM6Ly9kZXguYXV0aC5zdmMuY2x1c3Rlci5sb2NhbDo1NTU2 # Base64 Encoded value of dex URL i.e. https://dex.INSERT_OWN_DOMAIN.HERE
kind: Secret
metadata:
  labels:
    name: kube-oidc-proxy-config
  name: kube-oidc-proxy-config
  namespace: auth
type: Opaque
