apiVersion: v1
kind: Service
metadata:
  name: kube-oidc-proxy
  namespace: auth
spec:
  type: NodePort
  ports:
  - name: kube-oidc-proxy
    port: 8443
    protocol: TCP
    targetPort: 8443
    nodePort: 30443
  selector:
    name: kube-oidc-proxy
