apiVersion: v1
data:
  oidc.client-id: NzVVaU8yRTgxbTVWaTNuU1Q0MjY5ZnVP # Base64 encoded version of DEX staticClient config ClientID
  oidc.issuer-url: aHR0cHM6Ly9kZXguSU5TRVJUX09XTl9ET01JQU4uSEVSRQ== # Base64 Encoded value of dex URL i.e. https://dex.INSERT_OWN_DOMAIN.HERE
kind: Secret
metadata:
  labels:
    name: kube-oidc-proxy-config
  name: kube-oidc-proxy-config
  namespace: auth
type: Opaque
