apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    name: jumpbox
  name: jumpbox
  namespace: default
spec:
  dnsNames:
  - jumpbox.default.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: my-ca-issuer
  secretName: jumpbox-tls
