apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aks-kube-oidc-proxy.fullname" . }}
  labels:
    {{- include "aks-kube-oidc-proxy.labels" . | nindent 4 }}
name: {{ include "aks-kube-oidc-proxy.serviceAccountName" . }}
