kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "aks-kube-oidc-proxy.labels" . | indent 4 }}
  name: {{ include "aks-kube-oidc-proxy.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - "users"
  - "groups"
  - "serviceaccounts"
  verbs:
  - "impersonate"
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - "userextras/scopes"
  - "tokenreviews"
  verbs:
  - "create"
  - "impersonate"
