apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "aks-kube-oidc-proxy.fullname" . }}
  labels:
    {{- include "aks-kube-oidc-proxy.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ .Values.ingress.host }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: {{ .Values.tls.secretName }}
