{{- if .Values.ingress.enabled -}}
{{- $fullName := include "aks-kube-oidc-proxy.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "aks-kube-oidc-proxy.labels" . | nindent 4 }}
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
  tcpproxy:
    services:
      - name: {{ $fullName }}
        port: {{ $svcPort }}
  virtualhost:
    fqdn: {{ .Values.ingress.host }}
    tls:
      passthrough: true
