apiVersion: v1
data:
  gangway.yaml: |-
    {
      "apiServerURL": "https://localhost:30443",
      "authorizeURL": "https://aakindele-retaildevcrews-aks-oidc-proxy-rv7vjxgcx9j7-30556.githubpreview.dev/auth",
      "certFile": "/etc/gangway/tls/tls.crt",
      "clientID": "gangway-oauth2client",
      "clientSecret": "a5eedbeff37df5eeb67af65f",
      "clusterName": "codespace-k3d-cluster",
      "clusterCAPath": "/etc/gangway/tls/ca.crt",
      "keyFile": "/etc/gangway/tls/tls.key",
      "redirectURL": "https://aakindele-retaildevcrews-aks-oidc-proxy-rv7vjxgcx9j7-30080.githubpreview.dev/callback",
      "scopes": [
        "openid",
        "email",
        "profile",
        "groups",
        "offline_access"
      ],
      "serveTLS": false,
      "tokenURL": "http://dex.auth.svc.cluster.local:5556/token",
      "usernameClaim": "name"
    }
kind: ConfigMap
metadata:
  labels:
    name: gangway
  name: gangway
  namespace: auth
