apiVersion: v1
kind: Service
metadata:
  name: gangway
  namespace: auth
spec:
  type: ClusterIP
  ports:
  - name: gangway
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: gangway
