apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    name: gangway
  name: gangway
  namespace: auth
spec:
  dnsNames:
  - gangway.INSERT_OWN_DOMAIN.HERE
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: gangway-tls