apiVersion: v1
data:
  session-security-key: b2tWMXJtMjg2NnAzV284ZWNta1ZFNm5mRkkzak9MZlNuYU1iVXM4ZG5oaz0=
kind: Secret
metadata:
  labels:
    name: gangway
  name: gangway
  namespace: auth
type: Opaque
